language: ruby
sudo: false
cache:
  apt: true
  bundler: true
  directories:
  - vendor/something
  - .autoconf
rvm:
  - 2.2.3
env:
  - DB=sqlite
bundler_args: --without production
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - # bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec

addons:
  apt:
    packages:
      - silversearcher-ag
